import Head from 'next/head'
import Blogs from '../components/Sections/Blogs'
import Intro from '../components/Sections/Intro'
import Projects from '../components/Sections/Projects'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mijan Karim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Intro/>
        <Projects/>
        <Blogs/>
      </div>

    </div>
  )
}
